### ISSUE TITLE
Simple Server / Setup and Simple Server / Using refer to different directories

### ISSUE THREAD

**Issue by halostatue** [hofstadter-io/hof-docs#4]
https://docs.hofstadter.io/first-example/simple-server/setup/ says to make a directory `examples/`; https://docs.hofstadter.io/first-example/simple-server/using/ puts the example files in `example/`.

**Comment by verdverm** [comment]
I think to make things clearer, even for myself
1. the module being created should have its own "examples" directory, which means making everything plural (filenames and links)
2. that the top-level "example" (working directory) for the module being created should be renamed to "my-module"

so the tree looks like 

```
my-module/
  ...
  examples/
```

rather than

```
example/
  ...
  example(s)/
```

It seems a safe assumption that module authors will provide multiple example**s**.

**Comment by verdverm** [comment]
should be clearer now
